---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: rpms-signature-scan
  labels:
    app.kubernetes.io/version: "0.2.1"
spec:
  description: |-
    Scans RPMs in an image and provide information about RPMs signatures.
  params:
    - name: image-url
      type: string
      description: Image URL
    - name: image-digest
      type: string
      description: Image digest to scan
    - name: workdir
      type: string
      default: /tmp
      description: |
        Directory that will be used for storing temporary
        files produced by this task.
    - name: ca-trust-config-map-name
      type: string
      description: The name of the ConfigMap to read CA bundle data from.
      default: trusted-ca
    - name: ca-trust-config-map-key
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data.
      default: ca-bundle.crt
  results:
    - name: TEST_OUTPUT
      description: Tekton task test output.
    - name: RPMS_DATA
      description: Information about signed and unsigned RPMs
    - name: IMAGES_PROCESSED
      description: Images processed in the task.
  volumes:
    - name: workdir
      emptyDir: {}
    - name: trusted-ca
      configMap:
        name: $(params.ca-trust-config-map-name)
        items:
          - key: $(params.ca-trust-config-map-key)
            path: ca-bundle.crt
        optional: true
  steps:
    - name: rpms-signature-scan
      image: quay.io/konflux-ci/tools@sha256:735b102f82a4253e9a90687b414ca69e75edbbc2ebc9231d41f8eabc843eb3f5
      computeResources:
        limits:
          memory: 256Mi
          cpu: 200m
        requests:
          memory: 256Mi
          cpu: 200m
      volumeMounts:
        - name: workdir
          mountPath: "$(params.workdir)"
        - name: trusted-ca
          mountPath: /etc/pki/tls/certs/ca-custom-bundle.crt
          subPath: ca-bundle.crt
          readOnly: true
      env:
        - name: IMAGE_URL
          value: "$(params.image-url)"
        - name: IMAGE_DIGEST
          value: "$(params.image-digest)"
        - name: WORKDIR
          value: "$(params.workdir)"
      script: |
        #!/bin/bash
        set -ex
        set -o pipefail

        rpm_verifier \
          --image-url "${IMAGE_URL}" \
          --image-digest "${IMAGE_DIGEST}" \
          --workdir "${WORKDIR}" \
    - name: output-results
      image: quay.io/konflux-ci/konflux-test:v1.4.48@sha256:9b815268fb2bf10b5d745518da1c6568944f15816efe51adc192972b42a6e74d
      computeResources:
        limits:
          memory: 32Mi
          cpu: 50m
        requests:
          memory: 32Mi
          cpu: 50m
      volumeMounts:
        - name: workdir
          mountPath: "$(params.workdir)"
      env:
        - name: WORKDIR
          value: "$(params.workdir)"
      script: |
        #!/bin/bash
        set -ex

        source /utils.sh
        status=$(cat "${WORKDIR}"/status)
        rpms_data=$(cat "${WORKDIR}"/results)
        images_processed=$(cat "${WORKDIR}"/images_processed)

        if [ "$status" == "ERROR" ]; then
          note="Task $(context.task.name) failed to scan images. Refer to Tekton task output for details"
        else
          note="Task $(context.task.name) completed successfully"
        fi

        TEST_OUTPUT=$(make_result_json -r "$status" -t "$note")

        echo "${TEST_OUTPUT}" | tee "$(results.TEST_OUTPUT.path)"
        echo "${rpms_data}" | tee "$(results.RPMS_DATA.path)"
        echo "${images_processed}" | tee "$(results.IMAGES_PROCESSED.path)"
